### ISSUE TITLE
Unable to open file or directory from terminal

### ISSUE THREAD

**Issue by jwogrady** [Fred-Barclay/Termination#11]
Thanks for all your work on this....

I'm unable to open a file or folder from a termination shell.

```shell
projects $ atom .
LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.
projects $ atom README.md
LSOpenURLsWithRole() failed for the application /Applications/Atom.app with error -10810.
```
Everything works as expected if I run the commands outside of Atom in a standalone shell.

#### Using
- macOS Sierra v 10.12.1
- Atom 1.12.2
- termination 0.3.2

**Comment by Fred-Barclay** [comment]
Hmmm... I see that too in Linux. I'll investigate it - thanks!

For reference, this is the Linux output:
```
$ atom /home/fred/Git/Astro/lunar_phase.py
$ /usr/share/atom/atom: bad option: --executed-from=/home/fred/Git/Astro
/usr/share/atom/atom: bad option: --pid=25889
```

**Comment by Fred-Barclay** [comment]
@jwogrady Can you see if the same behavior occurs with platformio-ide-terminal? That will help narrow down the search a lot.
If it is occurring with platformio-ide-terminal, could you open an issue on their page as well (but **don't** close this one!). They know their code the best, and while I'll definitely keep trying to track this down it would help to have another set of eyes looking at the problem. If they fix it before I do then I'll integrate the changes back here.

Cheers!

**Comment by chrisallenmoore** [comment]
I'm getting the same error as @jwogrady. What's interesting is that I had a Java update right before I had this problem. Could the two be related?

**Comment by jwogrady** [comment]
@Fred-Barclay platformio-ide-terminal didn't seem to make a diffeerence.

@chrisallenmoore what Java version are you using?  Mine is as follows:

java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by Fred-Barclay** [comment]
@chrisallenmoore What OS are you using?
If it's a *nix, then what shell?

I haven't figured out the **why** yet, but for some reason termination (and platformio-ide-terminal, and possibly terminal-plus) replaces `atom` with `node` or `nodejs`.

**Comment by chrisallenmoore** [comment]
macOS Sierra
Version 10.12.2 Beta (16C48b)

**Comment by Fred-Barclay** [comment]
chrisallenmoore: thanks. :+1: What shell do you use?

**Comment by Fred-Barclay** [comment]
Update: there's a similar issue https://github.com/platformio/platformio-atom-ide-terminal/issues/106 so I'll keep an eye on that as well. 

@jwogrady What happens when you open the developer console (`ctrl+shift+i` though it might be `cmd+shift+i` for Mac) and run `atom <some-file>`? I get nothing on Linux but was wondering if there might be some output for Mac.

**Comment by chrisallenmoore** [comment]
I use the standard Mac terminal. Atom will open from there, but not in Termination.

**Comment by Fred-Barclay** [comment]
What happens if you run `sudo atom <some-command>`?

**Comment by chrisallenmoore** [comment]
@Fred-Barclay that works. hmmm

**Comment by Fred-Barclay** [comment]
Temporary workaround: go to the settings for termination and set `unset ELECTRON_RUN_AS_NODE` to run on terminal initialisation.

**Comment by jwogrady** [comment]
Sweet, thanks for the workaround!

Just to follow up, the atom debug/console running on Mac didn't give me any output to share.  [This ancient article related to PHPStorm](http://moazzam-khan.com/blog/tag/lsopenurlswithrole-failed-with-error-10658-for-the-file-applicationsphpstorm-app/) suggests a java versioning issue.

Your workaround shows a little output on mac every time I open a new instance of the terminal, but it works great.

```shell
unset ELECTRON_RUN_AS_NODE
project $ unset ELECTRON_RUN_AS_NODE
project $ 
```
I left the issue open in case you are still working on a final fix.  From my standpoint though the issue is closed.

Thanks again for all your work on this!

**Comment by Fred-Barclay** [comment]
Thanks mate! I'm still working on a permanent fix but at least I now know this workaround is good for both Linux and Mac. :+1: 
I believe the offending code is this (in Atom): https://github.com/atom/atom/blob/master/src/buffered-node-process.js#L40
`options.env.ELECTRON_RUN_AS_NODE = 1`

So I'm working on how to undo that **without** breaking Atom in any way.

**Comment by DamnedScholar** [comment]
I've opened an issue [on the Atom repo](https://github.com/atom/atom/issues/13624).

**Comment by Fred-Barclay** [comment]
Great! I was a little hesitant to do that myself since I didn't know if this was a bug in my code or an issue with Atom, hence my post on the Atom forums asking for help. Thanks for taking the initiative and opening the issue on the Atom repo! :smile:

**Comment by Naki21** [comment]
I have been having the same issues and I think I may have solved it. See my post in #33 .

It looks like ATOM_SHELL_INTERNAL_RUN_AS_NODE was renamed to ELECTRON_RUN_AS_NODE (https://github.com/atom/atom/pull/11475)

In the terminal ide `process.coffee` file the `filteredEnvironment` function still uses `ATOM_SHELL_INTERNAL_RUN_AS_NODE`. I changed this to `ELECTRON_RUN_AS_NODE` and it seems to now run the terminal properly. Let me know if this helps!

**Comment by Fred-Barclay** [comment]
@Naki21 Thanks! I've pushed out a new release with `ELECTRON_RUN_AS_NODE`. :smile:

@chrisallenmoore @jwogrady Please update to release 0.5.0 and let me know if this fixes the problem.
