### ISSUE TITLE
Status bar seems off/wrong

### ISSUE THREAD

**Issue by Traverse** [Fred-Barclay/Termination#14]
Hi

I just noticed something small on the bottom left of the status bar:

![statusbar](https://cloud.githubusercontent.com/assets/7240988/20483797/4f67ea18-aff4-11e6-8083-926d96c0fc9d.png)

There's some text down there and I have no clue what it is. The only thing I know is that it's happening only with this package enabled.

Also I'm not sure if it's intended or not but Termination's status bar doesn't show up all the time sometimes it just disappears.

Atom 1.12.5 on Windows 8.1 Pro

Kind regards!

**Comment by Fred-Barclay** [comment]
Hi @Traverse. That text is probably the cursor position (the `somefile Number:Number`  notice). You can check if this is the case by hovering over the status bar and scrolling down. To return to Termination's status bar, simply hover over the status bar again and scroll up.
(Side note: that's probably the cause of the termination's status bar disappearing sometimes - you might have inadvertently scrolled down.)

If you don't like this behavior, simply go to Termination's settings, tick the "Clone Terminal Plus" box, and restart Atom. 

Cheers, and thanks for the report!
Fred
