### ISSUE TITLE
scrolling ability

### ISSUE THREAD

**Issue by AnkitApurv** [Fred-Barclay/Termination#16]
ability to scroll through the terminal window to see previous command history, that would make this package awesome

**Comment by AnkitApurv** [comment]
i would be happy to help in this regard too

**Comment by Fred-Barclay** [comment]
Hi @AnkitApurv :smile: 

What OS are you using?
I can scroll through the terminal and see my history from the time I opened the terminal (though not my history from previous terminal sessions). In Linux and macOS as well, you should be able to hit the up arrow key and see your previous commands. I'll see if I can make a GIF/video of what I mean.

**Comment by AnkitApurv** [comment]
Hi, thanks for getting back so quickly :~)

I'm using Windows 10 build 14393(anniversary) x64
Atom 1.12.7

It does not show any scrollbar

It defaults to powershell in which if I press pageup, previous text progressively disappear(weird, I'l make a video later)
I changed it to command prompt(cmd) in which pageup/pagedown had no effect

**Comment by Fred-Barclay** [comment]
@AnkitApurv I've got a Windows box at work - I'll check it and see if I can duplicate this. Thanks for the report, and please send that video. :)

**Comment by AnkitApurv** [comment]
I've made the videos, they are on this link.
[https://1drv.ms/f/s!AobQnTtzCVMBlI539E2FkxGEOKlSew](url)

**Comment by Fred-Barclay** [comment]
Hmmm... that's odd. I can't duplicate it on Windows 7 but I see what you're talking about. So when you scroll in Power Shell, your text disappears. It looks like cmd behaves properly??? (BTW: there is no scroll bar in termination but you should still be able to scroll up and down.)

Can you do me a favour - try copying your Atom config folder (it should be `.atom` in your home folder) to a backup destination, then delete the folder. Now launch Atom and don't install anything but termination. Does that change anything?

(To revert, delete `.atom` again and copy your old folder from the backup destination.)

**Comment by AnkitApurv** [comment]
sorry for being so late with this, I checked, by moving my .atom folder from my profile and doing a fresh termination install, it behaved the same, problem remains

**Comment by Fred-Barclay** [comment]
Certainly it's worth a try. :smile:
