### ISSUE TITLE
Forking your repo

### ISSUE THREAD

**Issue by pmbenjamin** [Fred-Barclay/Termination#17]
@Fred-Barclay, I'm having difficulty forking your repo because I already have forked [platformio/platformio-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) since your repo is also a fork of the same repo.

Any suggestions on how to fork you repo without affecting the [platformio/platformio-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) fork?

**Comment by Fred-Barclay** [comment]
It could be a bit complicated (yikes, didn't think of that earlier). Would you mind me just manually copying your changes from the platformio pull request? I'll still make sure to credit you. :smile: 

*Or* according to http://stackoverflow.com/questions/12338240/how-can-i-fork-the-original-repo-when-ive-already-forked-a-different-fork#12339396 you can choose to open your original pull request here without forking my repo... not sure how to do that though.

**Comment by Fred-Barclay** [comment]
Looks like you made it!
