### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by kutulus** [Fred-Barclay/Termination#20]
Argument to `path.dirname` must be a string
```
Object.dirname (/Users/stefano/Desktop/Atom Beta.app/Contents/Resources/app.asar/src/electron-shims.js:9:10)
<unknown> (/Users/stefano/.atom/packages/termination/lib/status-bar.coffee:248:59)
Function.module.exports.Emitter.simpleDispatch (/Users/stefano/Desktop/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
Emitter.emit (/Users/stefano/Desktop/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
<unknown> (/Users/stefano/Desktop/Atom Beta.app/Contents/Resources/app.asar/src/pane-container.js:348:27)
Function.module.exports.Emitter.simpleDispatch (/Users/stefano/Desktop/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
```

**Comment by Fred-Barclay** [comment]
Hi kutulus! Thanks for the report!
Is this more of a cosmetic issue (which still needs to be fixed, of course), or does it actively interfere/stop you from using termination?

Cheers!
Fred

**Comment by kutulus** [comment]
Hi Fred,
sorry for the late reply.
It seems to have no effect to the functionality....

**Comment by Fred-Barclay** [comment]
@kutulus: Thanks. :+1: 
Is this still for Atom Beta? What are the steps to replicate it?

**Comment by kutulus** [comment]
Hi,
no, it also appears in Atom 1.13.0

Running on OSX 10.11.6
No special installation (I think)
I started using it after some problems with Terminal Plus...

Atom 1.13.0:
Argument to path.dirname must be a string

    Object.dirname - /Applications/02_coding/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:9:10
    <unknown> - /Users/stefano/.atom/packages/termination/lib/status-bar.coffee:248:59
    Function.module.exports.Emitter.simpleDispatch - /Applications/02_coding/Atom.app/Contents /Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14
    Emitter.emit - /Applications/02_coding/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28
    <unknown> - /Applications/02_coding/Atom.app/Contents/Resources/app.asar/src/pane-container.js:348:27
    Function.module.exports.Emitter.simpleDispatch - /Applications/02_coding/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14

**Comment by Fred-Barclay** [comment]
Oh, I see. :-) I can't replicate it here though (Atom 1.13, Arch Linux). Could you maybe take a screenshot or walk me through exactly what you have to do to get this to happen?

**Comment by kutulus** [comment]
Hi,
-- installed via Settings -> Install ->Install Packages
-- Enable termination
-- Quit and Start Atom
-- In the Statusbar at the bottom appears an Info...

<img width="1075" alt="screenshot" src="https://cloud.githubusercontent.com/assets/8246670/22305922/987c4dda-e33d-11e6-9662-5fff2fc66d6a.png">

**Comment by Fred-Barclay** [comment]
Perfect! :smile: I still can't replicate it but there's a PR upstream that references this. I've asked the chap if he'd like to submit his PR here, and if not, I'll fix it myself.
Thanks!

**Comment by benphelps** [comment]
🚢

**Comment by kutulus** [comment]
Appying #21 to  lib/status-bar.coffee works fine for me.

thanks!

**Comment by Fred-Barclay** [comment]
Great news! Thanks @benphelps for the fix. :+1: 
@kutulus thanks for the report and for trying termination!

**Comment by saeidamiri1** [comment]
Hi Fred-Barclay, 
 I got deprecations after using shift+alt+R  (mac and Atom 1.19.0).
Thanks, S. 

<img width="1273" alt="screen shot 2017-08-12 at 12 24 47" src="https://user-images.githubusercontent.com/19543946/29242818-5e49954c-7f59-11e7-9888-81a00a7b868b.png">
