### ISSUE TITLE
Option to place the terminal window on the right

### ISSUE THREAD

**Issue by yochem** [Fred-Barclay/Termination#29]
It would be cool if you had the option to place the terminal window on the right side of atom, like a split screen. I would like to help you, but I'm not the best at java- and coffeescript. 

Version of Atom: **1.14.3**
Version of Termination: **0.3.6**
Operating System: **macOS Sierra 10.12.2**

**Comment by Fred-Barclay** [comment]
G'day @yochem :)
That's a great idea! We do have something similar already, though it's not obvious (I actually didn't know it existed until about a week ago :smile: ) thanks to Atom's panes. Start a terminal and then drag the icon up to the file tabs bar. The pull the tab to the right and slightly down. You should get a two-pane view with your editor in the left pane and termination in the right:

![capture](https://cloud.githubusercontent.com/assets/11165995/23166318/119d7400-f838-11e6-9620-170e978aa585.PNG)

Is that something like you're thinking?

It is a bit inconvenient at the moment, so I'll definitely look into making it simpler to do.

Cheers!
Fred

**Comment by yochem** [comment]
Awesome! exactly what I meant. Been trying to do something like this with panes, but didn't get the result I wanted. It's true it's a bit inconvenient, but it works :) thank you for all your hard work!

**Comment by Fred-Barclay** [comment]
Great! I'm going to mark this closed then, and I've already added making this easier to the TODO file 684c42c594ea1dc84856e62f7ee27681f9eed0ee.

Cheers!
Fred

**Comment by yochem** [comment]
You're a hero! thanks :)
