### ISSUE TITLE
Cannot bind Left/Right/Up/Down keys in terminatal/termination

### ISSUE THREAD

**Issue by jdamour98** [Fred-Barclay/Termination#31]
In the atom work space, the editor receives key commands (i.e. `cmd-left` goes to the start of the line). However, one cannot ever bind the directional keys in termination, because they seem to not come through. Using the keybind-resolver (`cmd-.`), I cannot force the directional keys to ever appear while viewing the terminal. 

I'd like to bind `cmd-left` and `cmd-right' to `termination:prev` and `termination:next` respectively.

Atom@1.14.3
Termination@0.3.7
OS@OSX10.12.3

**Comment by Fred-Barclay** [comment]
G'day @jdamour98 . I'll look into it, thanks! :smile:
Fred

**Comment by jdamour98** [comment]
Thanks for the quick reply and label! I understand this isn't an issue/bug/important, but thought I'd add it to the discussion. Appreciate the attention!

**Comment by Fred-Barclay** [comment]
I just did some snooping around (admittedly on a linux machine so it might not be accurate) and it appears that `cmd-left` and `cmd-right` are reserved already.

We do offer the `alt-shift-j` and `alt-shift-k` keybindings for `termination:prev` and `termination:next` respectively.

Hope this helps!
Fred
