### ISSUE TITLE
Question: vertical view

### ISSUE THREAD

**Issue by janl** [Fred-Barclay/Termination#36]
I’m wondering if it would be possible to have the terminal work in a vertical view?

Imagine a widescreen display, 80col source code panels and then just one extra column for the terminal, makes it easier to read stackstraces and whatnot.

|code|code|term|

**Comment by yochem** [comment]
I think you mean something similar to issue #29, let me know if this helps you out

**Comment by janl** [comment]
brilliant, thank you. I did look through closed issue, but probably with the wrong search terms. Thanks!

**Comment by yochem** [comment]
No problem! Glad i could help 😄
