### ISSUE TITLE
Uncaught TypeError: Cannot read property 'focusTerminal' of null

### ISSUE THREAD

**Issue by adkelley** [Fred-Barclay/Termination#38]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [termination](https://github.com/Fred-Barclay/Termination) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'focusTerminal' of null

```
At /Users/Gibson/.atom/packages/termination/lib/status-bar.coffee:26

TypeError: Cannot read property 'focusTerminal' of null
    at /packages/termination/lib/status-bar.coffee:26:46)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:04.6.0 termination:focus (input.hidden-input)
```

### Non-Core Packages

```
atom-fix-path 0.1.0 
atom-terminal 0.8.0 
atomic-emacs 0.10.0 
autocomplete-haskell 0.7.2 
build 0.67.0 
busy 0.7.0 
busy-signal 1.3.0 
haskell-ghc-mod 1.19.7 
ide-haskell 1.9.6 
ide-haskell-cabal 1.9.0 
ide-purescript 0.15.3 
ink 0.6.5 
intentions 1.1.2 
language-babel 2.56.2 
language-elm 1.5.0 
language-haskell 1.12.1 
language-matlab 0.2.1 
language-purescript 0.8.2 
linter 2.1.0 
linter-elm-make 0.23.1 
linter-eslint 8.1.4 
linter-hlint 1.0.1 
linter-stylelint 3.9.0 
linter-ui-default 1.1.0 
lisp-paredit 0.5.5 
Parinfer 1.17.0 
proto-repl 1.4.17 
Stylus 3.1.0 
termination 0.5.0 
```

**Comment by Fred-Barclay** [comment]
Thanks for the report! I'll look into it. 
I don't have a mac so I might need you to do some testing; is that okay?

**Comment by Fred-Barclay** [comment]
(Sorry, didn't mean to close it.)

**Comment by adkelley** [comment]
No worries, I'm happy to help.  I was attempting to switch to the terminal window (cmd-option-f) when it wasn't open.  As long as the terminal window is open (ctrl-~) then atom won't throw the error.  Perhaps you catch the error and display a friendly "No terminal window is open" message before atom throws throws the error?  Thanks!

**Comment by Fred-Barclay** [comment]
@adkelley I've just added a PR from upstream that should hopefully fix this. Can you do
```
apm uninstall termination
apm install Fred-Barclay/termination
```
to get the latest code in this repo and see if it works?

Currently it's just set to do nothing if a terminal window isn't opened, but I might change that based on how well this works. 😄 
Thanks!

**Comment by adkelley** [comment]
Yes. It's working for me.  Thank you!

**Comment by Fred-Barclay** [comment]
Awesome, thanks!
I'll push out a new version in a few hours, then.

**Comment by pietrodn** [comment]
Glad that my fix helped! :)

**Comment by Fred-Barclay** [comment]
@pietrodn Thanks so much! 😁
