### ISSUE TITLE
[Feature] Option to disable toggle animation 

### ISSUE THREAD

**Issue by charliesbox** [Fred-Barclay/Termination#40]

**Comment by MarleDK** [comment]
If you just set the animation speed to 0, it will be off.

**Comment by Fred-Barclay** [comment]
Thanks @MarleDK . That's the correct answer - just go to Settings (Ctrl + ,) in Atom, "Packages", "Termination", and then select our settings. From there you can set animation speed to 0 (it's 1 by default).

**Comment by nicman23** [comment]
there should be info about 0 -> disables animation on the tooltip

**Comment by Fred-Barclay** [comment]
@nicman23 Done, thanks!
