### ISSUE TITLE
Better theme compatibility 

### ISSUE THREAD

**Issue by stillworks** [Fred-Barclay/Termination#41]
With the default theme selecting the open terminal windows with the little icons works well. With for exp. Atom Material theme not.

They flicker and can't be clicked. I have to click between the terminal icon and the line under the icon so switch between the different terminals. Seems the size gets messed up somehow.

[I made a video](https://spaces.hightail.com/space/Lqu5s/fi-d519e4f8-1cc0-407d-9b06-4c1c784027d3/fv-45fcdd51-d5ce-4641-b34f-3bb3d4affb55/Atom%20Termination%20Problem.mp4)

Newest Atom, Termination, macOS

**Comment by Fred-Barclay** [comment]
Woah, that is an issue! I'll look into it. :smile: 

Thanks for trying Termination!

**Comment by girlandhercode** [comment]
This is also an #[issue](https://github.com/platformio/platformio-atom-ide-terminal/issues/149) with [Platform.io's version of the terminal](https://github.com/platformio/platformio-atom-ide-terminal) for Atom when used in combination with Atom Material theme and someone already mentioned a fix that worked for me (and others apparently).

[Link to comment with fix](https://github.com/platformio/platformio-atom-ide-terminal/issues/149#issuecomment-275125816)

Fix by @kbrgl:

> I've been experiencing the same issue with atom-material-ui. How did you disable the transition from devtools?
EDIT: Nvm, I figured it out. Adding this to my stylesheet fixed the problem:
```
.tooltip {
  transition: opacity 500ms;
}
```
> The problem is that atom-material-ui adds unnecessary transitions to the transform property of tooltips. This resets it to only having transitions on the tooltip opacity.

**Comment by stillworks** [comment]
Agreed, that fixed it for me. Thanks!

**Comment by Fred-Barclay** [comment]
Thank you @girlandhercode! 
So it **is** a bit buggy (imho) but not on our end. This info and the workaround are definitely going into the wiki. :smile: 

Cheers!
Fred
