### ISSUE TITLE
Allow hiding the "close all" button

### ISSUE THREAD

**Issue by cdzombak** [Fred-Barclay/Termination#52]
**Environment:** Atom 1.17.2, macOS 10.12.5, Termination 0.5.1.

Termination's "Close All" button is always displayed in the status bar:

<img width="439" alt="screen shot 2017-06-14 at 17 27 02" src="https://user-images.githubusercontent.com/102904/27155381-c76a5f54-5126-11e7-8efb-d819316bdaa2.png">

**Feature request:** I'd prefer having some way to hide it, even if terminals are open. I rarely work with more than one or two terminals, and for me it's not worth the extra visual clutter it adds.

Thanks for your work on this useful package!

**Comment by saadq** [comment]
I agree that it would be nice if this was a built-in feature, but it's pretty easily doable with a little CSS. You can even remove the entire top-bar and bottom bar if you'd like. Here is what mine's looks like:

![screen shot 2017-07-09 at 6 30 00 pm](https://user-images.githubusercontent.com/5678694/27998116-a481e888-64d4-11e7-96c6-3768d972c1af.png)

If you just want to get rid of "Close All" button, you can just add the following to your stylesheet:

```scss
.termination {
  &.status-bar .icon-x {
    display: none;
  }
}
```

**Comment by cdzombak** [comment]
That's a great idea. Thanks, @saadq!
