### ISSUE TITLE
Termination terminal UI not visible, keybinds not working on Atom 1.19

### ISSUE THREAD

**Issue by 16patsle** [Fred-Barclay/Termination#57]
### Description

After updating to the newly released Atom 1.19, the terminal UI added by this package is no longer visible. The toolbar under the editor is not there, and the keybindings and menu elements seem to do nothing. Could be related to #56.

### Steps to Reproduce

1. Use/update to Atom 1.19
2. Have the package activated
3. Notice the lack of UI
4. Try using the keybindings
5. Notice how nothing happens

**Expected behavior:** Visible termination UI, keybinds and menu elements work

**Actual behavior:** UI not visible, keybinds and menu elements not working

**Reproduces how often:** Seems to reproduce all the time

### Versions
Atom: 1.19.0
Electron: 1.6.9
Chrome: 56.0.2924.87
Node: 7.4.0
OS: macOS Sierra 10.12.6

### Additional Information

```
Community Packages (30)
├── atom-beautify@0.30.4
├── atom-clock@0.1.13
├── atom-ternjs@0.18.3
├── busy-signal@1.4.3
├── caniuse@0.9.2
├── docblockr@0.11.0
├── editor-stats@0.17.0
├── editorconfig@2.2.2
├── emmet@2.4.3
├── file-icons@2.1.10
├── flex-tool-bar@0.12.0
├── intentions@1.1.5
├── language-apache@1.7.0
├── language-gitignore@0.3.0
├── language-markdown@0.25.1
├── linter@2.2.0
├── linter-eslint@8.2.1
├── linter-stylelint@4.0.1
├── linter-ui-default@1.6.3
├── minimap@4.29.3
├── minimap-linter@2.0.2
├── minimap-pigments@0.2.2
├── pigments@0.40.1
├── project-manager@3.3.5
├── riot-tag@1.1.1
├── termination@0.5.1
├── todo-show@1.11.0
└── tool-bar@1.1.0
```

**Comment by Fred-Barclay** [comment]
Hi, sorry about this. Hopefully it's fixed now with the 0.6.0 release. After updating, Atom may tell you to rebuild Termination due to incompatibilities... just click the red bug icon and follow the prompts.

**Comment by VladimirDev93** [comment]
`Linux Mint 18.2 amd64`

After the `0.6.0` release, all good.

**Comment by 16patsle** [comment]
Thanks. After updating and rebuilding, there seems to be no problems anymore. 👍🏼
