### ISSUE TITLE
Uncaught ReferenceError: fromWindowEvent is not defined

### ISSUE THREAD

**Issue by adkelley** [Fred-Barclay/Termination#59]
[Enter steps to reproduce:]

1.  Start a termination session (ctrl-`)
2.  This uncaught reference error occurs whenever I switch back to Atom from another application.  I can also reproduce it by focusing on the termination window with my mouse, instead of ctrl-alt-f 

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [termination](https://github.com/Fred-Barclay/Termination) package 0.5.1

### Stack Trace

Uncaught ReferenceError: fromWindowEvent is not defined

```
At /Users/Gibson/.atom/packages/termination/lib/view.coffee:446

ReferenceError: fromWindowEvent is not defined
    at TerminationView.module.exports.TerminationView.focus (/packages/termination/lib/view.coffee:446:27)
    at TerminationView.focus (/packages/termination/lib/view.coffee:1:1)
    at /packages/termination/lib/status-bar.coffee:124:25
```

### Commands

```
  2x -5:13.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
alex-word-count 0.0.0 
atom-fix-path 0.1.0 
atom-terminal 0.8.0 
atomic-emacs 0.12.0 
autocomplete-haskell 1.0.0 
build 0.68.0 
busy 0.7.0 
busy-signal 1.4.3 
haskell-ghc-mod 2.0.6 
ide-haskell 2.0.3 
ide-haskell-cabal 2.0.0 
ide-purescript 0.18.1 
ink 0.7.4 
intentions 1.1.5 
language-babel 2.70.2 
language-elm 1.5.0 
language-haskell 1.12.1 
language-idris 0.4.9 
language-lfe 0.1.0 
language-lisp 0.2.0 
language-matlab 0.2.1 
language-purescript 0.8.2 
linter 2.2.0 
linter-elm-make 0.23.7 
linter-eslint 8.2.1 
linter-hlint 1.0.1 
linter-stylelint 4.0.1 
linter-ui-default 1.6.4 
parinfer 1.20.0 
proto-repl 1.4.21 
Stylus 3.1.1 
termination 0.5.1 
```

**Comment by Fred-Barclay** [comment]
I've just pushed a new version to fix a different error when running Termination on Atom 1.19 - can you update to that and let me know if the problem persists?

**Comment by adkelley** [comment]
Yes, running your new version of Termination on Atom 1.19 appears to have fixed the problem.  Thanks!
