### ISSUE TITLE
Feature request: pipe to terminal

### ISSUE THREAD

**Issue by jberkus** [Fred-Barclay/Termination#64]
One thing I'd love to have for Termination would be the ability to take highlighted text from the current text buffer in Atom, and with a menu option "pipe" it to the terminal.

This was functionality I added to Kate (editor) once upon a time, but the Atom code baffles me.

So ... name your price?

**Comment by Fred-Barclay** [comment]
Would https://github.com/Fred-Barclay/Termination#insert-selected-text be what you are looking for?

**Comment by Fred-Barclay** [comment]
Haha, no worries. :) I can't take credit - the functionality was added either by the platformio guys or @jeremyramin.
