### ISSUE TITLE
What is a terminal?

### ISSUE THREAD

**Issue by DannyMcGillick** [Fred-Barclay/Termination#70]
Hey guys, I know it might sound silly at first, please don’t take this as snark :) I couldn’t find a definition for terminal anywhere in the Readme and I genuinely want to know what it opens on the different platforms. On windows is it command prompt, powershell or ubuntu for windows? Can I choose which one in config? It’d be great to have that communicated somewhere in the “terminal” section of the readme. Thanks for reading.
I

**Comment by Fred-Barclay** [comment]
G'day @DannyMcGillick !
On Windows, the default behavior is to open powershell, although you can set it to use cmd by default (which is what I do).
On Linux, macOS, and other *Nixes the default is bash - again, you can change it in the Settings >> Shell Override.
![shell](https://user-images.githubusercontent.com/11165995/36708595-5f5ed66e-1b39-11e8-9dd9-895f42868aec.png)

The relevant code snippet is below (from lib/termination.coffee):
```
        shell:
          title: 'Shell Override'
          description: 'Override the default shell instance to launch.'
          type: 'string'
          default: do ->
            if process.platform is 'win32'
              path = require 'path'
              path.resolve(process.env.SystemRoot, 'System32', 'WindowsPowerShell', 'v1.0', 'powershell.exe')
            else
              process.env.SHELL || '/bin/bash'
```
We really should document this - thanks for pointing it out!

**Comment by DannyMcGillick** [comment]
Thankyou for being so understanding, and helpful!

**Comment by Fred-Barclay** [comment]
No worries mate. Cheers!
