### ISSUE TITLE
Terminal doesn't let me type anything

### ISSUE THREAD

**Issue by norman123123** [Fred-Barclay/Termination#71]
The terminal doesn't initialize and it doesn't let me type anything. It won't print any errors or messages, just the blinking cursor.

<img width="1141" alt="screen shot 2018-03-21 at 11 15 16" src="https://user-images.githubusercontent.com/8712696/37714782-27cbd1ee-2cf9-11e8-8ddb-3a730c867ae9.png">

**Comment by mdtdev** [comment]
I am having the same problem on OSX. I would report errors but no messages appear.

**Comment by Fred-Barclay** [comment]
Sorry about this, guys. I believe it's the same issue our upstream is facing:
https://github.com/platformio/platformio-atom-ide-terminal/issues/493
https://github.com/platformio/platformio-atom-ide-terminal/issues/490
https://github.com/platformio/platformio-atom-ide-terminal/issues/477

They have a fix out, but it doesn't seem to be working for all users. I'll look into it and post back ASAP!

Cheers!
Fred

**Comment by mdtdev** [comment]
Thank you for looking into this! If there is any additional information I can provide, let me know.

**Comment by Fred-Barclay** [comment]
@norman123123 @mdtdev I've been puzzling over why I can't replicate this myself on my home system (Linux) but can on my work desktop (Windows 7), and then I realized I build from the latest code here on GitHub for my home desktop. So...
Can you please run the following for me and see if it helps:
```
apm uninstall Termination
```
Then check ~/.atom/packages/ to make sure that the Termination folder really is gone.
Finally,
```
apm install Fred-Barclay/Termination
```
will install from latest here on GitHub.

If that works I'll push out a fix soon.
Thanks!
Fred

**Comment by mdtdev** [comment]
I can confirm that the above version `Fred-Barclay/Termination` works on my Windows 10 system. I will attempt to replicate this on OS X later today. I am not able to get to my Mac just now.

**Comment by mdtdev** [comment]
Sorry for the delay! I can confirm that the OS X version works for me, too. Thanks for the help!

When you push the fix, I assume that I have to APM uninstall the branch version then reinstall from the main the usual way?

Thanks for your work on this project!

**Comment by Fred-Barclay** [comment]
@mdtdev Thanks! I've pushed the new version. You will have to `apm uninstall Termination` first, and then reinstall from main as usual.

Cheers and thanks for the help!
Fred
