### ISSUE TITLE
Can't get Termination to work.

### ISSUE THREAD

**Issue by NiklasPeterson** [Fred-Barclay/Termination#77]
After running the command npm install -g node-gyp in Mac terminal and installing the Termination package into Atom and trying to open a new terminal inside Atom nothing happens.

Please help me out!

**Comment by JRetza** [comment]
Ditto - Termination stopped functioning:
![screen shot 2018-06-22 at 12 17 52 pm](https://user-images.githubusercontent.com/16158547/41789885-6430cd2c-7616-11e8-948a-500f6008acac.png)

@Fred-Barclay we'll take a look over the weekend - let us know if we can help with anything here.

**Comment by the-j0k3r** [comment]
This wont work wit Atom 1.28 you need to upgrade your pty binaries to m57 for compatibility with electron 2.0.3, only thing you can do is compile them or upgrade to node-pty-prebuilt which also has no working windows binaries for electron 2.0.3 for 0.7.5 relase

**Comment by Fred-Barclay** [comment]
Hey guys,
Termination 0.6.3 is out which should fix this. Please update and let me know!
