### ISSUE TITLE
Feature Request: Rename color names in settings

### ISSUE THREAD

**Issue by canderis** [Fred-Barclay/Termination#78]
I like to use particular colors to represent what is running in each terminal, such as a node server, angular dev server, mongo, and ssh.
I overrode some of the colors but it would be nicer if I could rename the colors so that Orange wasn't pointing to a green!

Would be cool to be able to add a few more too.

**Comment by canderis** [comment]
I honestly forgot about this! 
I believe I had changed the "Orange" color in the settings to point to a green color but it still said orange even though the color was actually green.

I switched to a different IDE now, however, so I no longer have that configuration to show.

**Comment by Fred-Barclay** [comment]
Oh, I see. Thanks! I'll close this then. :smile:
