### ISSUE TITLE
Keeps blinking

### ISSUE THREAD

**Issue by pooriamo** [Fred-Barclay/Termination#80]
Hi

I used to use Platformio but I had the problem that the cursor kept blinking and I couldn't type. So I switched to Termination. But the same thing is still happening!

OS: Windows 10 64-bit 10.0.17134
Atom version: 1.27.2
Termination: Latest

**Comment by ronasimi** [comment]
Was a solution ever found for this?

**Comment by Fred-Barclay** [comment]
I'll close for now since this seems to have fixed in 9eb2296fecfd44092d7f5a1e267e563e046b07f7. Let me know if this is still an issue!
Fred
