### ISSUE TITLE
Error at open Termination

### ISSUE THREAD

**Issue by paulrm** [Fred-Barclay/Termination#84]
I got the following two lines before the bash prompt 

```
bash: mc: line 1: syntax error: unexpected end of file
bash: error importing function definition for `mc'
```
any Idea who to debug and fix?

OS: openSUSE Leap 42.3
Atom: 1.26.1
Termination: 0.6.3

**Comment by Fred-Barclay** [comment]
@paulrm Does this issue still exist in the latest version of Termination (v0.7.1)?

**Comment by Fred-Barclay** [comment]
Closing for now. @paulrm please feel free to reopen if this is still an issue for the latest release. :smile:
