### ISSUE TITLE
unable to type backslash \ in terminal

### ISSUE THREAD

**Issue by trusktr** [Fred-Barclay/Termination#85]
Hello, this is by far the best terminal package for Atom. Nice work!

One issue I have is I can't type a backslash (`\`) in the terminal. I can get by without it, but thought I'd open an issue. Any ideas?

**Comment by Fred-Barclay** [comment]
Hi @trusktr,
Sorry for the late reply. :smile: What OS/distro are you using? I can't replicate this on Windows 7 or any Linux distro I've tried.
Cheers!
Fred

**Comment by Fred-Barclay** [comment]
Closing for now (hopefully 9eb2296fecfd44092d7f5a1e267e563e046b07f7 squashed this). Feel free to re-open if this is still an issue!
