### ISSUE TITLE
I don't see any termination commands or UI in Windows

### ISSUE THREAD

**Issue by trusktr** [Fred-Barclay/Termination#95]
When I try Atom in Windows with the Termination plugin, there's no UI at the bottom, and the command palette shows no Termination commands.

Does it work in Windows?

**Comment by Fred-Barclay** [comment]
It works for me on Windows 7, and when I last used it on Windows 10 as well (but that's been a while). What version are you using?

**Comment by Fred-Barclay** [comment]
Closing for now. @trusktr feel free to re-open if this is still an issue
